apiVersion: apps/v1
kind: Deployment
metadata:
  name: jwt-micro-deployment
  labels:
    app: micro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: micro
  template:
    metadata:
      labels:
        app: micro
    spec:
      containers:
      - name: micro
        image: shekharpyne/spring-jwt
        ports:
        - containerPort: 8761