apiVersion: v1
kind: Service
metadata: 
  name: nifi-demo
  labels: 
    app: nifi-demo
    name: nifi
spec: 
  type: LoadBalancer
  ports: 
  - port: 8080
    targetPort: 8080
  selector:
    name: nifi-deployment-demo
    app: nifi
