apiVersion: v1
kind: Service
metadata: 
  name: nifi
  labels: 
    app: nifi
    name: nifi-service
spec: 
  type: LoadBalancer
  ports: 
  - port: 8080
    targetPort: 8080
  selector:
    name: nifi-pod
