apiVersion: v1
kind: Pod
metadata:
  name: nifi-deployment-demo
  labels:
    name: nifi-deployment-demo
    app: nifi
spec:
    containers:
    - name: nifi
      image: apache/nifi:1.9.1
      ports:
      - containerPort: 8080