apiVersion: v1
kind: Service
metadata: 
  name: nifi
  labels: 
    app: nifi
    name: nifi-service
spec: 
  ports: 
  - port: 8080
	image: "apache/nifi:1.9.1"
	targetPort: 8080
    selector:
	  name: nifi-pod
      
